# Generated by Django 5.0.6 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedflowerimage',
            name='confidence_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedflowerimage',
            name='confidence_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedflowerimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedflowerimage',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedflowerimage',
            name='name_latin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='uploadedflowerimage',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
